---
name: build

# on:
#   push:
#     paths:
#       - .github/workflows/build.yml
#       - Dockerfile.alpine
#       - Dockerfile.debian
#       - Dockerfile.redhat
#   pull_request:
#     paths:
#       - .github/workflows/build.yml
#       - Dockerfile.alpine
#       - Dockerfile.debian
#       - Dockerfile.redhat
#   schedule:
#     - cron: "42 10 * * 1"
#
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generating commit logs
        run: |
          cd commits
          ./generate_3+year.sh
